LOCAL_PATH := .
include $(CLEAR_VARS)
include $(GAPPS_CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := Music2
LOCAL_PACKAGE_NAME := com.google.android.music

GAPPS_LOCAL_OVERRIDES_PACKAGES := Music Eleven

include $(BUILD_GAPPS_PREBUILT_APK)
