LOCAL_PATH := .
include $(CLEAR_VARS)
include $(GAPPS_CLEAR_VARS)
LOCAL_MODULE := TVLauncher
LOCAL_PACKAGE_NAME := com.google.android.tvlauncher.leanback
GAPPS_LOCAL_OVERRIDES_PACKAGES := TVLauncherNoGMS
LOCAL_PRIVILEGED_MODULE := true

include $(BUILD_GAPPS_PREBUILT_APK)
