LOCAL_PATH := .
include $(CLEAR_VARS)
include $(GAPPS_CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := GoogleContacts
LOCAL_PACKAGE_NAME := com.google.android.contacts
LOCAL_PRIVILEGED_MODULE := true

GAPPS_LOCAL_OVERRIDES_MIN_VARIANT :=
GAPPS_LOCAL_OVERRIDES_PACKAGES := Contacts

include $(BUILD_GAPPS_PREBUILT_APK)
