LOCAL_PATH := .
include $(CLEAR_VARS)
include $(GAPPS_CLEAR_VARS)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE := LatinImeGoogle
LOCAL_PACKAGE_NAME := com.google.android.inputmethod.latin

GAPPS_LOCAL_OVERRIDES_MIN_VARIANT :=
GAPPS_LOCAL_OVERRIDES_PACKAGES := LatinIME

include $(BUILD_GAPPS_PREBUILT_APK)
